# Meta Data for SEO

## Homepage
title = "Wheat Free Recipes"
titleSeparator = "-"
titleAddition = "Gluten free, wheat free, fast and easy."
description = "A scrumptious collection of gluten free, wheat free recipes that are fast and easy to make."

## Documentation
# docsVersion = "0.3"

## Open Graph
# images = [""]
ogLocale = "en_US"
domainTLD = "wheatfreerecipe.com"
titleHome = "WheatFreeRecipe"

## Twitter Cards
twitterCreator = "@MrsSueDunham"

## JSON-LD
# schemaType = "Person"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"
smallLimit = "300"

# Images
imageResponsive = true
imageConvertTo = "webp"
imageImageSizes = ["480","720","1080","1280","1600","2048"]
singleSize = false
imageAddClass = "img-fluid lazyload blur-up"

### Image template
defaultImage = "default-image.png" # put in `./assets/images/`
fillImage = "1270x740 Center" # normalize image size

# Footer
footer = "❤️"

# Feed
copyRight = "Copyright (c) 2023"

# Alert
alert = false
alertDismissable = true
# alertText = ""

# Edit Page
# repoHost [Github | Gitea | GitLab | Bitbucket | BitbucketServer ] is used for building the edit link based on git hoster
#repoHost = "GitHub"
#repoHost = "Gitea"
#docsRepo = "https://github.com/"
#docsRepoBranch = "master"
#docsRepoSubPath = ""
editPage = false
lastMod = false

[sections]
  sectionNav = ["blog", "recipes"]

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = true
  searchSectionsShow = []
  searchSectionsIndex = []
  darkMode = true
  bootStrapJs = true
  breadCrumb = false
  highLight = true
  kaTex = false
  multilingualMode = false
  docsVersioning = false
  fullWidth = false
  navbarSticky = true
  toTopButton = false
  scrollSpy = false # experimental; needs Bootstrap >= 5.2.0-beta1

[menu]
  [menu.section]
    auto = true
    collapsibleSidebar = true
